### ISSUE TITLE
Is it possible to have more than one delete or put on a single page?

### ISSUE THREAD

**Issue by alexbannon** [ga-dc/wdinstagram#3]
Title says it all, but for example.

/photos/:id

I want the ability to have a button that deletes the photo, but I want another button that can delete comments below the photo (I had comment functionality)

**Comment by mattscilipoti** [comment]
tl;dr Yes.

Each form in a view is an independent entity, with its own action and html method.  Just have each form submit to the appropriate route and it will work as you want.
